### ISSUE TITLE
Update checker thinks that the 1.20.2 variant is newer than the 1.20.1 variant at the same version

### ISSUE THREAD

**Issue by GlynLeine** [pluto7073/PlutosCoffeeMod-Fabric#10]
As the title says:
![image](https://github.com/user-attachments/assets/4df9de05-df04-4a56-a041-20b44eb754ab)
Clicking "Okay" crashes minecraft

**Comment by pluto7073** [comment]
I ended up removing update checker in the latest release because it was buggy and hard to maintain so this is no longer an issue
